require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

# Several methods are structured to be identical cross-language. So there is no point flagging them constantly
Metrics:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

RSpec/MessageSpies:
  EnforcedStyle: receive
