#!perl

requires 'perl' => '5.14.4';
requires 'Moo';
requires 'List::Util' => '1.63'; # for 'any' and 'all' functions.

on 'test' => sub {
    requires 'Test2::V0';
    requires 'Test2::Tools::Exception';
    requires 'YAML';
};
